// utils/mapCountryToMarket.ts

export const countryMarketMap: { [key: string]: string } = {
  // South East Asia
  'Brunei': 'South East Asia',
  'Cambodia': 'South East Asia',
  'East Timor (Timor-Leste)': 'South East Asia',
  'Indonesia': 'South East Asia',
  'Laos': 'South East Asia',
  'Malaysia': 'South East Asia',
  'Myanmar (Burma)': 'South East Asia',
  'Philippines': 'South East Asia',
  'Singapore': 'South East Asia',
  'Thailand': 'South East Asia',
  'Vietnam': 'South East Asia',
  
  // East Asia
  'China': 'East Asia',
  'Japan': 'East Asia',
  'Mongolia': 'East Asia',
  'North Korea': 'East Asia',
  'South Korea': 'East Asia',
  'Taiwan': 'East Asia',
  
  // South Asia
  'Afghanistan': 'South Asia',
  'Bangladesh': 'South Asia',
  'Bhutan': 'South Asia',
  'India': 'South Asia',
  'Maldives': 'South Asia',
  'Nepal': 'South Asia',
  'Pakistan': 'South Asia',
  'Sri Lanka': 'South Asia',
  
  // Europe
  'Albania': 'Europe',
  'Andorra': 'Europe',
  'Armenia': 'Europe',
  'Austria': 'Europe',
  'Azerbaijan': 'Europe',
  'Belarus': 'Europe',
  'Belgium': 'Europe',
  'Bosnia and Herzegovina': 'Europe',
  'Bulgaria': 'Europe',
  'Croatia': 'Europe',
  'Cyprus': 'Europe',
  'Czech Republic': 'Europe',
  'Denmark': 'Europe',
  'Estonia': 'Europe',
  'Finland': 'Europe',
  'France': 'Europe',
  'Georgia': 'Europe',
  'Germany': 'Europe',
  'Greece': 'Europe',
  'Hungary': 'Europe',
  'Iceland': 'Europe',
  'Ireland': 'Europe',
  'Italy': 'Europe',
  'Kazakhstan (partly in Europe)': 'Europe',
  'Kosovo': 'Europe',
  'Latvia': 'Europe',
  'Liechtenstein': 'Europe',
  'Lithuania': 'Europe',
  'Luxembourg': 'Europe',
  'Malta': 'Europe',
  'Moldova': 'Europe',
  'Monaco': 'Europe',
  'Montenegro': 'Europe',
  'Netherlands': 'Europe',
  'North Macedonia': 'Europe',
  'Norway': 'Europe',
  'Poland': 'Europe',
  'Portugal': 'Europe',
  'Romania': 'Europe',
  'Russia (partly in Europe)': 'Europe',
  'San Marino': 'Europe',
  'Serbia': 'Europe',
  'Slovakia': 'Europe',
  'Slovenia': 'Europe',
  'Spain': 'Europe',
  'Sweden': 'Europe',
  'Switzerland': 'Europe',
  'Turkey (partly in Europe)': 'Europe',
  'Ukraine': 'Europe',
  'United Kingdom': 'Europe',
  'Vatican City': 'Europe',
  
  // Latin America
  'Argentina': 'Latin America',
  'Belize': 'Latin America',
  'Bolivia': 'Latin America',
  'Brazil': 'Latin America',
  'Chile': 'Latin America',
  'Colombia': 'Latin America',
  'Costa Rica': 'Latin America',
  'Cuba': 'Latin America',
  'Dominican Republic': 'Latin America',
  'Ecuador': 'Latin America',
  'El Salvador': 'Latin America',
  'Guatemala': 'Latin America',
  'Guyana': 'Latin America',
  'Haiti': 'Latin America',
  'Honduras': 'Latin America',
  'Jamaica': 'Latin America',
  'Mexico': 'Latin America',
  'Nicaragua': 'Latin America',
  'Panama': 'Latin America',
  'Paraguay': 'Latin America',
  'Peru': 'Latin America',
  'Suriname': 'Latin America',
  'Trinidad and Tobago': 'Latin America',
  'Uruguay': 'Latin America',
  'Venezuela': 'Latin America',
  'Antigua and Barbuda': 'Latin America',
  'Bahamas': 'Latin America',
  'Barbados': 'Latin America',
  'Dominica': 'Latin America',
  'Grenada': 'Latin America',
  'Saint Kitts and Nevis': 'Latin America',
  'Saint Lucia': 'Latin America',
  'Saint Vincent and the Grenadines': 'Latin America',
  
  // North America
  'Canada': 'North America',
  'United States of America': 'North America',
  
  // Middle East and North Africa
  'Algeria': 'Middle East and North Africa',
  'Bahrain': 'Middle East and North Africa',
  'Egypt': 'Middle East and North Africa',
  'Iran': 'Middle East and North Africa',
  'Iraq': 'Middle East and North Africa',
  'Israel': 'Middle East and North Africa',
  'Jordan': 'Middle East and North Africa',
  'Kuwait': 'Middle East and North Africa',
  'Lebanon': 'Middle East and North Africa',
  'Libya': 'Middle East and North Africa',
  'Morocco': 'Middle East and North Africa',
  'Oman': 'Middle East and North Africa',
  'Palestine': 'Middle East and North Africa',
  'Qatar': 'Middle East and North Africa',
  'Saudi Arabia': 'Middle East and North Africa',
  'Syria': 'Middle East and North Africa',
  'Tunisia': 'Middle East and North Africa',
  'United Arab Emirates': 'Middle East and North Africa',
  'Yemen': 'Middle East and North Africa',
  
  // Oceania
  'Australia': 'Oceania',
  'Fiji': 'Oceania',
  'Kiribati': 'Oceania',
  'Marshall Islands': 'Oceania',
  'Micronesia': 'Oceania',
  'Nauru': 'Oceania',
  'New Zealand': 'Oceania',
  'Palau': 'Oceania',
  'Papua New Guinea': 'Oceania',
  'Samoa': 'Oceania',
  'Solomon Islands': 'Oceania',
  'Tonga': 'Oceania',
  'Tuvalu': 'Oceania',
  'Vanuatu': 'Oceania',
  
  // Other
  'Angola': 'Other',
  'Benin': 'Other',
  'Botswana': 'Other',
  'Burkina Faso': 'Other',
  'Burundi': 'Other',
  'Cameroon': 'Other',
  'Cape Verde': 'Other',
  'Central African Republic': 'Other',
  'Chad': 'Other',
  'Comoros': 'Other',
  'Democratic Republic of the Congo': 'Other',
  'Djibouti': 'Other',
  'Equatorial Guinea': 'Other',
  'Eritrea': 'Other',
  'Eswatini': 'Other',
  'Ethiopia': 'Other',
  'Gabon': 'Other',
  'Gambia': 'Other',
  'Ghana': 'Other',
  'Guinea': 'Other',
  'Guinea-Bissau': 'Other',
  'Ivory Coast': 'Other',
  'Kenya': 'Other',
  'Lesotho': 'Other',
  'Liberia': 'Other',
  'Madagascar': 'Other',
  'Malawi': 'Other',
  'Mali': 'Other',
  'Mauritania': 'Other',
  'Mauritius': 'Other',
  'Mozambique': 'Other',
  'Namibia': 'Other',
  'Niger': 'Other',
  'Nigeria': 'Other',
  'Republic of the Congo': 'Other',
  'Rwanda': 'Other',
  'São Tomé and Príncipe': 'Other',
  'Senegal': 'Other',
  'Seychelles': 'Other',
  'Sierra Leone': 'Other',
  'Somalia': 'Other',
  'South Africa': 'Other',
  'South Sudan': 'Other',
  'Sudan': 'Other',
  'Tanzania': 'Other',
  'Togo': 'Other',
  'Uganda': 'Other',
  'Zambia': 'Other',
  'Zimbabwe': 'Other'
};

// Map other countries to 'Other'
export function mapCountryToMarket(country: string): string {
  return countryMarketMap[country] || 'Other';
}
